- name: Create the user if it does not exist
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    state: present

- name: Copy identity file to remote host
  become: true
  ansible.builtin.copy:
    src: id.json
    dest: "{{ identity_keypair_file }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0600'

- name: Install a list of packages
  become: true
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - build-essential
      - pkg-config
      - libudev-dev
      - cmake
      - libclang-dev
      - libssl-dev
      - gparted
      - nload
      - python3-pip
      - net-tools
      - logind
      - curl
      - git
      - chrony
      - htop
      - acl
      - cpufrequtils
      - libsasl2-dev
      - libudev-dev 
      - pkg-config 
      - zlib1g-dev 
      - llvm 
      - clang 
      - make 
      - libprotobuf-dev 
      - protobuf-compiler
      - cargo
