- name: p3-txn-sender setup
  become: yes
  hosts: all
  vars:
    user: p3
    identity_keypair_file: /home/p3/id.json
    service: p3-txn-sender
    rust_version: 1.78.0
    rpc_url:
    grpc_url:
    x_token: 
    leader_offset: 0
    datadog_api_key: 
    datadog_site: 
    datadog_config:
      dogstatsd_port: 7998
      use_dogstatsd: true
      logs_enabled: true
      tags:
        - "staked:{{staked|default('false')}}"
        - "env:prod"
        - "service:p3_txn_sender"
        - "network:mainnet"
        - "region:{{region}}"
  tasks:
    - name: Execute datadog setup
      include_role:
       name: datadog-setup
    - name: Install haproxy
      include_role:
       name: haproxy-setup   
    - name: Install rust
      include_role:
       name: install-rust
    - name: Execute p3-txn-sender setup
      include_role:
       name: p3-txn-sender
