---
- name: check if rust is installed
  stat:
    path: "~/.cargo/bin/rustc"
  register: rust_exists
  become: no

- name: Install rust
  when: not rust_exists.stat.exists
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    executable: /bin/bash
  become: no

- name: set default rust version
  shell: source ~/.profile && rustup default stable
  when: rust_version is not defined and rust_exists.stat.exists
  args:
    executable: /bin/bash
  become: no

- name: set rust version
  shell: source ~/.profile && rustup default {{ rust_version }}
  when: rust_version is defined and rust_exists.stat.exists
  args:
    executable: /bin/bash
  become: no
